# Generated by Django 5.2.4 on 2026-02-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_schema_alignment'),
        ('trips', '0007_alter_trip_category_departrecurrent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='departure',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_voyage',
            field=models.DateField(blank=True, help_text='Date choisie par le client pour ce voyage', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='depart_recurrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trips.departrecurrent'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REUSSI', 'Reussi'), ('ECHOUE', 'Echoue'), ('ANNULE', 'Annule')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero de siege'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDEE', 'Validee'), ('CONFIRMEE', 'Confirmee'), ('REJETEE', 'Rejetee'), ('ANNULEE', 'Annulee'), ('EXPIREE', 'Expiree')], default='EN_ATTENTE_VALIDATION', max_length=25),
        ),
    ]
