# Generated by Django 5.2.4 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_depart_permanent_simple"),
        ("reservations", "0005_remove_reservation_departure_reservation_date_voyage_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DELETE FROM reservations_reservation WHERE depart_recurrent_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="UPDATE reservations_reservation SET date_voyage = date(booked_at) WHERE date_voyage IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="depart_recurrent",
            new_name="depart",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date_voyage",
            field=models.DateField(help_text="Date choisie par le client pour voyager"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="depart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="trips.depart",
            ),
        ),
    ]
