# Generated by Django 5.2.4 on 2026-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_depart_permanent_simple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='motif_rejet',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='validee_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='validee_par',
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmee'), ('ANNULEE', 'Annulee')], default='EN_ATTENTE', max_length=20),
        ),
    ]
