# Generated by Django 5.2.4 on 2026-02-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_alter_departure_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gare',
                'verbose_name_plural': 'Gares',
            },
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('permis', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducteurs', to='trips.bus')),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
            },
        ),
    ]
