# Generated by Django 5.2.4 on 2026-02-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gareci_admin', '0002_schema_alignment'),
        ('trips', '0007_alter_trip_category_departrecurrent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationconducteur',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_conducteurs', to='trips.departrecurrent'),
        ),
    ]
