# Generated by Django 5.2.4 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_depart_permanent_simple"),
        ("gareci_admin", "0003_alter_affectationconducteur_departure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affectationconducteur",
            name="departure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affectations_conducteurs",
                to="trips.depart",
            ),
        ),
    ]
