# Generated by Django 5.2.4 on 2026-02-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departure',
            options={'ordering': ['date', 'time']},
        ),
    ]
