# Generated by Django 5.2.4 on 2026-02-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_state_add_legacy_bus_departure_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartRecurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
                ('duree_minutes', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frequence', models.CharField(choices=[('QUOTIDIEN', 'Tous les jours'), ('LUN_VEN', 'Lundi au Vendredi'), ('WEEKEND', 'Samedi et Dimanche'), ('SPECIFIQUE', 'Jours specifiques')], default='QUOTIDIEN', max_length=20)),
                ('lundi', models.BooleanField(default=True)),
                ('mardi', models.BooleanField(default=True)),
                ('mercredi', models.BooleanField(default=True)),
                ('jeudi', models.BooleanField(default=True)),
                ('vendredi', models.BooleanField(default=True)),
                ('samedi', models.BooleanField(default=False)),
                ('dimanche', models.BooleanField(default=False)),
                ('date_debut', models.DateField(help_text='Date a partir de laquelle ce depart est actif')),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide = actif indefiniment', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.bus')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs_recurrents', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Depart recurrent',
                'verbose_name_plural': 'Departs recurrents',
                'ordering': ['heure_depart'],
            },
        ),
        migrations.AddField(
            model_name='departure',
            name='depart_recurrent',
            field=models.ForeignKey(blank=True, help_text='Null si ce depart a ete cree manuellement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='trips.departrecurrent'),
        ),
        migrations.AlterUniqueTogether(
            name='departure',
            unique_together={('depart_recurrent', 'date_depart')},
        ),
    ]
