# Generated by Django 5.2.4 on 2026-02-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gareci_admin', '0003_alter_affectationconducteur_departure'),
        ('reservations', '0005_remove_reservation_departure_reservation_date_voyage_and_more'),
        ('trips', '0007_alter_trip_category_departrecurrent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departrecurrent',
            options={'ordering': ['heure_depart'], 'verbose_name': 'Depart', 'verbose_name_plural': 'Departs'},
        ),
        migrations.RemoveField(
            model_name='departrecurrent',
            name='duree_minutes',
        ),
        migrations.RemoveField(
            model_name='departrecurrent',
            name='frequence',
        ),
        migrations.AddField(
            model_name='departrecurrent',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departrecurrent',
            name='dimanche',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='departrecurrent',
            name='samedi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='departrecurrent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='trips.trip'),
        ),
        migrations.DeleteModel(
            name='Departure',
        ),
    ]
