# Generated by Django 5.2.4 on 2026-02-22 17:13

import django.db.models.deletion
import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_departrecurrent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(default=trips.models.get_default_category_pk, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_trips', to='trips.category'),
        ),
    ]
