# Generated by Django 5.2.4 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0009_alter_trip_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DepartRecurrent",
            new_name="Depart",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="date_debut",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="date_fin",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="dimanche",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="jeudi",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="lundi",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="mardi",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="mercredi",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="samedi",
        ),
        migrations.RemoveField(
            model_name="depart",
            name="vendredi",
        ),
        migrations.RunSQL(
            sql="UPDATE trips_depart SET heure_arrivee = heure_depart WHERE heure_arrivee IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name="depart",
            options={"ordering": ["trip", "heure_depart"], "verbose_name": "Départ", "verbose_name_plural": "Départs"},
        ),
        migrations.AlterField(
            model_name="depart",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departs",
                to="trips.bus",
            ),
        ),
        migrations.AlterField(
            model_name="depart",
            name="heure_arrivee",
            field=models.TimeField(),
        ),
    ]
